"""is_basic added to CaKppMapping

Revision ID: 002
Revises: 001
Create Date: 2023-04-20 11:35:47.444553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bank', ['bic'])
    op.add_column('cakppmapping', sa.Column('is_basic', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cakppmapping', 'is_basic')
    op.drop_constraint(None, 'bank', type_='unique')
    # ### end Alembic commands ###
