"""ca group name instead of id

Revision ID: 003
Revises: 002
Create Date: 2023-04-20 14:17:24.581133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counteragent', sa.Column('group_name', sa.String(length=50), nullable=True))
    op.drop_constraint('counteragent_group_id_fkey', 'counteragent', type_='foreignkey')
    op.create_foreign_key(None, 'counteragent', 'counteragentgroup', ['group_name'], ['name'])
    op.drop_column('counteragent', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counteragent', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'counteragent', type_='foreignkey')
    op.create_foreign_key('counteragent_group_id_fkey', 'counteragent', 'counteragentgroup', ['group_id'], ['id'])
    op.drop_column('counteragent', 'group_name')
    # ### end Alembic commands ###
