"""first migration

Revision ID: ec51c566353b
Revises: 
Create Date: 2023-03-02 14:47:28.495471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec51c566353b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('bic', sa.Integer(), nullable=False),
    sa.Column('correspondent_account', sa.String(length=20), nullable=True),
    sa.Column('payment_city', sa.String(length=50), nullable=False),
    sa.Column('swift', sa.String(length=11), nullable=True),
    sa.Column('registration_number', sa.Integer(), nullable=True),
    sa.Column('treasury_accounts', sa.String(length=20), nullable=True),
    sa.Column('opf_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('inn', sa.Integer(), nullable=True),
    sa.Column('kpp', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('actuality_date', sa.DateTime(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('liquidation_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bic'),
    sa.UniqueConstraint('inn', 'kpp', name='_inn_kpp_unique'),
    sa.UniqueConstraint('name')
    )
    op.create_table('counteragent',
    sa.Column('on_behalf', sa.Boolean(), nullable=True),
    sa.Column('ogrn', sa.String(length=20), nullable=True),
    sa.Column('ogrn_date', sa.DateTime(), nullable=True),
    sa.Column('counteragent_type', sa.String(length=50), nullable=True),
    sa.Column('opf_short', sa.String(length=10), nullable=True),
    sa.Column('name_short_with_opf', sa.String(length=150), nullable=True),
    sa.Column('ip_surname', sa.String(length=100), nullable=True),
    sa.Column('ip_name', sa.String(length=100), nullable=True),
    sa.Column('ip_patronymic', sa.String(length=100), nullable=True),
    sa.Column('management_name', sa.String(length=300), nullable=True),
    sa.Column('management_post', sa.String(length=100), nullable=True),
    sa.Column('address_full_with_index', sa.String(length=300), nullable=True),
    sa.Column('address_egrul', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('inn', sa.Integer(), nullable=True),
    sa.Column('kpp', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('actuality_date', sa.DateTime(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('liquidation_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn', 'kpp', name='_inn_kpp_unique'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bankaccount',
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.Column('ca_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.ForeignKeyConstraint(['ca_id'], ['counteragent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', 'bank_id', name='_account_bank_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bankaccount')
    op.drop_table('counteragent')
    op.drop_table('bank')
    # ### end Alembic commands ###
